### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by Chebotarev** [appacademy-prep-work/appacademy-prep-work.github.io#6]
A student on piazza:

Hey, so I’m going back over the debugging part here. The issue is, there are two files which the links are broken. Anyone have an idea where these files are? .pryrc and .rdebugrc

**Comment by chungkikelly** [comment]
Found a .pryrc file in the dotfile repo, but not a .rdebugrc file.
https://github.com/appacademy/dotfiles/tree/master/dot

**Comment by wolverdude** [comment]
Fixed by #10
