### ISSUE TITLE
most_common_letter instructions

### ISSUE THREAD

**Issue by ruggeri** [appacademy-prep-work/appacademy-prep-work.github.io#9]
The instructions to `most_common_letter` talk about counting something in an array. You don't get an array, you get a string. Please change the reference of array to string.

This involves updating the repl.it item, so someone will have to do that for me.

Alex, could you help?

**Comment by Chebotarev** [comment]
Resolved by commit:
https://github.com/appacademy-prep-work/appacademy-prep-work.github.io/commit/1cbea12119c29f1a496f645b0a2ff05f8158690f

**Comment by Chebotarev** [comment]
Thanks for finding that Ned!
